### ISSUE TITLE
It's not stable

### ISSUE THREAD

**Issue by itlodge** [hzqtc/fmd#8]
It's a great job! But it's sometimes not stable. Sometimes I run fmd but I can't find the process when I look for "ps -e".

**Comment by hzqtc** [comment]
Have you checked out `~/.fmd/fmd.err` and `~/.fmd/fmd.log`?
If you still can't figure out the problem, please attach them here.
Thanks.

**Comment by itlodge** [comment]
## fmd.err:

ao_alsa ERROR: Unable to open ALSA device 'default' for playback => Invalid argument
Open audio output: Input/output error

## fmd.conf:

[Output]
driver = alsa
device = default
rate = 44100

## /etc/libao.conf:

default_driver=alsa
dev=default

I try change 'default' to 'front', but there are no sound!

**Comment by itlodge** [comment]
Oh, I have found why this will happen. Everytime I hit "fmc end", I must wait for several minutes so that I can hit "fmc play" again.

**Comment by hzqtc** [comment]
Glad you made it!
I don't recommand `fmc end`, `killall fmd` is prefered. Because `fmc end` will leave the tcp connection in `wait-close` mode for several minutes, during which time `fmd` can't get started because the tcp port is still in use.

PS: I almost never try to kill fmd at all. I just `fmd toogle` when I am tired of it.
